#!/bin/bash
set -e

echo "1. Moving UI components to packages/ui..."
cp -a apps/sajucube-mweb/src/components/* packages/ui/src/

echo "2. Adding @repo/saju-core dependency to packages/ui..."
sed -i 's/"dependencies": {/"dependencies": {\n    "@repo\/saju-core": "workspace:*",/g' packages/ui/package.json

echo "3. Replacing imports in packages/ui..."
# In the components, they import from "@/lib/...".
# We only moved korean-lunisolar, manselyeok, chasam-manselyeok, birth-text to saju-core.
# So we only replace imports matching those exact paths.
for file in packages/ui/src/*.tsx packages/ui/src/*.ts; do
  if [ -f "$file" ]; then
    sed -i 's|@/lib/korean-lunisolar|@repo/saju-core|g' "$file"
    sed -i 's|@/lib/manselyeok|@repo/saju-core|g' "$file"
    sed -i 's|@/lib/chasam-manselyeok|@repo/saju-core|g' "$file"
    sed -i 's|@/lib/birth-text|@repo/saju-core|g' "$file"
    
    # Wait, some might import like @/lib/manselyeok-share, etc. which are not in saju-core if not moved.
    # We did move all files matching 'manselyeok*' 'korean-lunisolar*' 'chasam-manselyeok*' 'birth-text*'.
    
    # Fix self-referential component imports: @/components/... -> ./...
    # Since all components are now flat in packages/ui/src/
    sed -i -E 's|@/components/([^"'\''\\]+)|./\1|g' "$file"
  fi
done

echo "4. Replacing imports in apps/sajucube-mweb..."
for file in $(find apps/sajucube-mweb/src -type f -name "*.tsx" -o -name "*.ts"); do
  # Fix core imports
  sed -i 's|@/lib/korean-lunisolar|@repo/saju-core|g' "$file"
  sed -i 's|@/lib/manselyeok|@repo/saju-core|g' "$file"
  sed -i 's|@/lib/chasam-manselyeok|@repo/saju-core|g' "$file"
  sed -i 's|@/lib/birth-text|@repo/saju-core|g' "$file"
  
  # Fix ui imports
  sed -i -E 's|@/components/([^"'\''\\]+)|@repo/ui/\1|g' "$file"
done

echo "5. Updating sajucube-mweb dependencies for UI..."
# Actually sajucube-mweb probably already has @repo/ui if it was generated by turbo. Let's check.
# If not, add it.
if ! grep -q '"@repo/ui"' apps/sajucube-mweb/package.json; then
  sed -i 's/"dependencies": {/"dependencies": {\n    "@repo\/ui": "workspace:*",/g' apps/sajucube-mweb/package.json
fi

echo "6. Deleting old components folder from sajucube-mweb..."
rm -rf apps/sajucube-mweb/src/components

echo "7. Installing dependencies..."
pnpm install

echo "UI Migration script completed."
